version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    depends_on:
      - db
    volumes: 
      - ./backend:/app/backend
  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes: 
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=reality_check
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

volumes:
  db-data:
    name: db_volume
