"""empty message

Revision ID: 138cbadfee3e
Revises: 695a0ec19099
Create Date: 2024-03-09 10:09:47.623052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '138cbadfee3e'
down_revision = '695a0ec19099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=mysql.VARCHAR(length=510),
               type_=sa.String(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('fact_combinations', schema=None) as batch_op:
        batch_op.alter_column('facts',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('narrative_events', schema=None) as batch_op:
        batch_op.alter_column('resulting_headline',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('resulting_photo_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('primary_narratives', schema=None) as batch_op:
        batch_op.alter_column('headline',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('photo_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('secondary_narratives', schema=None) as batch_op:
        batch_op.alter_column('resulting_headline',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('resulting_photo_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secondary_narratives', schema=None) as batch_op:
        batch_op.alter_column('resulting_photo_url',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('resulting_headline',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('primary_narratives', schema=None) as batch_op:
        batch_op.alter_column('photo_url',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('headline',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('narrative_events', schema=None) as batch_op:
        batch_op.alter_column('resulting_photo_url',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('resulting_headline',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('fact_combinations', schema=None) as batch_op:
        batch_op.alter_column('facts',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=510),
               existing_nullable=False)

    # ### end Alembic commands ###
