"""Reconfigured table layout. Understood needs better as I build app.

Revision ID: 21126849f6c0
Revises: c1dd6e9bef6a
Create Date: 2024-02-26 11:02:32.300406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21126849f6c0'
down_revision = 'c1dd6e9bef6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_combinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facts', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrative_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narrative_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('resulting_headline', sa.String(length=255), nullable=False),
    sa.Column('resulting_story', sa.Text(), nullable=False),
    sa.Column('resulting_photo_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['narrative_id'], ['primary_narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('narrative_fact_associations')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=510), nullable=False))
        batch_op.alter_column('language',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_column('event')

    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=255), nullable=False))
        batch_op.alter_column('language',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_column('fact')
        batch_op.drop_column('is_key_fact')

    with op.batch_alter_table('primary_narratives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fact_combination_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('narrative_text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('language', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('story', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('headline',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'fact_combinations', ['fact_combination_id'], ['id'])
        batch_op.drop_column('photo')
        batch_op.drop_column('narrative')
        batch_op.drop_column('news_story')

    with op.batch_alter_table('secondary_narratives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_narrative_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_fact_combination', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('narrative_text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('resulting_headline', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('resulting_story', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('resulting_photo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('secondary_narratives_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('secondary_narratives_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('secondary_narratives_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'primary_narratives', ['original_narrative_id'], ['id'])
        batch_op.drop_column('outcome')
        batch_op.drop_column('event_id')
        batch_op.drop_column('narrative')
        batch_op.drop_column('user_id')
        batch_op.drop_column('parent_narrative_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secondary_narratives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_narrative_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('narrative', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('outcome', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('secondary_narratives_ibfk_2', 'primary_narratives', ['parent_narrative_id'], ['id'])
        batch_op.create_foreign_key('secondary_narratives_ibfk_1', 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key('secondary_narratives_ibfk_3', 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('resulting_photo_url')
        batch_op.drop_column('resulting_story')
        batch_op.drop_column('resulting_headline')
        batch_op.drop_column('narrative_text')
        batch_op.drop_column('updated_fact_combination')
        batch_op.drop_column('original_narrative_id')

    with op.batch_alter_table('primary_narratives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_story', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('narrative', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('photo', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('headline',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('story')
        batch_op.drop_column('language')
        batch_op.drop_column('narrative_text')
        batch_op.drop_column('fact_combination_id')

    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_key_fact', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fact', mysql.TEXT(), nullable=False))
        batch_op.alter_column('language',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('text')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', mysql.TEXT(), nullable=False))
        batch_op.alter_column('language',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('text')

    op.create_table('narrative_fact_associations',
    sa.Column('narrative_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fact_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], name='narrative_fact_associations_ibfk_1'),
    sa.ForeignKeyConstraint(['narrative_id'], ['primary_narratives.id'], name='narrative_fact_associations_ibfk_2'),
    sa.PrimaryKeyConstraint('narrative_id', 'fact_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('narrative_events')
    op.drop_table('fact_combinations')
    # ### end Alembic commands ###
