"""Add updated_fact_combination_id to SecondaryNarrative

Revision ID: 695a0ec19099
Revises: 9bd1754121b7
Create Date: 2024-03-08 10:41:44.817587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '695a0ec19099'
down_revision = '9bd1754121b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secondary_narratives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_fact_combination_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'fact_combinations', ['updated_fact_combination_id'], ['id'])
        batch_op.drop_column('updated_fact_combination')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secondary_narratives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_fact_combination', mysql.VARCHAR(length=500), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_fact_combination_id')

    # ### end Alembic commands ###
