"""Added language into User model

Revision ID: 9bd1754121b7
Revises: 21126849f6c0
Create Date: 2024-02-26 19:46:28.525706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bd1754121b7'
down_revision = '21126849f6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.Enum('ENG', 'EST', 'RUS', name='language_types'),
               existing_nullable=False)

    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.Enum('ENG', 'EST', 'RUS', name='language_types'),
               existing_nullable=False)

    with op.batch_alter_table('primary_narratives', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.Enum('ENG', 'EST', 'RUS', name='language_types'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('primary_narratives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', mysql.VARCHAR(length=80), nullable=False))

    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.Enum('ENG', 'EST', 'RUS', name='language_types'),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.Enum('ENG', 'EST', 'RUS', name='language_types'),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
